In [1]:
import pandas as pd
import re

In [2]:
data1=pd.read_csv('../dataproject/20112015.csv')
data2=pd.read_csv('../dataproject/20162020.csv')

In [3]:
data1

        일자   상승  하락
0   201101  171  19
1   201102  167   9
2   201103   94  19
3   201104   66  27
4   201105   96  48
5   201106  100  28
6   201107   58  34
7   201108   88  11
8   201109   68  15
9   201110   47  27
10  201111   36  29
11  201112   72  51
12  201201   67  23
13  201202   52  16
14  201203   55  31
15  201204   30  45
16  201205   32  30
17  201206   41  34
18  201207   35  63
19  201208   52  84
20  201209   34  48
21  201210   51  58
22  201211   61  51
23  201212   57  51
24  201301   46  66
25  201302   63  38
26  201303   64  51
27  201304   70  19
28  201305   64  21
29  201306   53  44
30  201307   57  41
31  201308   68  36
32  201309   76  25
33  201310   92  26
34  201311   66  25
35  201312  102  26
36  201401  123  24
37  201402  129  24
38  201403  115  14
39  201404   57  32
40  201405   55  31
41  201406   58  27
42  201407   59  22
43  201408   79  10
44  201409   74  11
45  201410   62  10
46  201411  103  29
47  201412   85  23
48  201501   60   7
49  201502   83  10
50  201503  124  10
51  201504  127  13
52  201505   76   7
53  201506  138   5
54  201507   92  10
55  201508  109   9
56  201509  103   8
57  201510  105   6
58  201511  136  14
59  201512  117  25

In [4]:
real_data = pd.concat([data1,data2])

In [5]:
real_data

        일자   상승   하락
0   201101  171   19
1   201102  167    9
2   201103   94   19
3   201104   66   27
4   201105   96   48
5   201106  100   28
6   201107   58   34
7   201108   88   11
8   201109   68   15
9   201110   47   27
10  201111   36   29
11  201112   72   51
12  201201   67   23
13  201202   52   16
14  201203   55   31
15  201204   30   45
16  201205   32   30
17  201206   41   34
18  201207   35   63
19  201208   52   84
20  201209   34   48
21  201210   51   58
22  201211   61   51
23  201212   57   51
24  201301   46   66
25  201302   63   38
26  201303   64   51
27  201304   70   19
28  201305   64   21
29  201306   53   44
..     ...  ...  ...
30  201807   53   84
31  201808   54   33
32  201809   64   23
33  201810   81   49
34  201811   56   80
35  201812   67   69
36  201901   57  136
37  201902   19   99
38  201903   23   88
39  201904   34  105
40  201905   18   46
41  201906   31   60
42  201907   53   58
43  201908   52   44
44  201909   57   34
45  201910   83   42
46  201911   65   26
47  201912  101   24
48  202001   90   46
49  202002   97    9
50  202003   65   41
51  202004   55   34
52  202005   48   49
53  202006  108   27
54  202007  106   12
55  202008  179    7
56  202009  147    8
57  202010  118   15
58  202011  140    3
59  202012  177   14

[120 rows x 3 columns]

In [6]:
real_data.index = real_data['일자']

In [7]:
real_data=real_data.drop(columns='일자', axis=1)

In [8]:
real_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 120 entries, 201101 to 202012
Data columns (total 2 columns):
상승    120 non-null int64
하락    120 non-null int64
dtypes: int64(2)
memory usage: 2.8 KB

In [9]:
#real_data.to_csv('20112020.csv')

In [10]:
real_data

         상승   하락
일자
201101  171   19
201102  167    9
201103   94   19
201104   66   27
201105   96   48
201106  100   28
201107   58   34
201108   88   11
201109   68   15
201110   47   27
201111   36   29
201112   72   51
201201   67   23
201202   52   16
201203   55   31
201204   30   45
201205   32   30
201206   41   34
201207   35   63
201208   52   84
201209   34   48
201210   51   58
201211   61   51
201212   57   51
201301   46   66
201302   63   38
201303   64   51
201304   70   19
201305   64   21
201306   53   44
...     ...  ...
201807   53   84
201808   54   33
201809   64   23
201810   81   49
201811   56   80
201812   67   69
201901   57  136
201902   19   99
201903   23   88
201904   34  105
201905   18   46
201906   31   60
201907   53   58
201908   52   44
201909   57   34
201910   83   42
201911   65   26
201912  101   24
202001   90   46
202002   97    9
202003   65   41
202004   55   34
202005   48   49
202006  108   27
202007  106   12
202008  179    7
202009  147    8
202010  118   15
202011  140    3
202012  177   14

[120 rows x 2 columns]

In [11]:
data3 = pd.read_csv("../dataproject/주택매매가격지수(KB).csv", encoding="utf-8", engine="python")

In [12]:
data3=data3.iloc[ : ,0:2]

In [13]:
data3=data3.rename({'Unnamed: 0' : '일자'},axis='columns')

In [14]:
data3['일자'] = data3['일자'].astype(dtype= str)

In [15]:
data3['일자'][0][0:7]

'1986-01'

In [16]:
def date_cleaning(text):
    result = re.sub("-","",text)
    return result

In [17]:
data3['일자'] = data3['일자'].apply(lambda x : date_cleaning(x))

In [18]:
date = []
for x in data3['일자']:
    date.append(x[0:6])
data3['일자'] = date

In [19]:
data3.index = data3['일자']

In [20]:
data3=data3.drop(columns='일자')

In [21]:
data3 = data3['201101':'202012']

In [22]:
data3=data3.rename({'총지수[2019.01=100]' : '총지수'},axis='columns')

In [23]:
data3['총지수'] = data3['총지수'] - 0.576

In [33]:
data3.to_csv('주택매매지수.csv')

In [24]:
data4=pd.merge(data3,real_data, on = data3.index)

In [25]:
data4 = data4.rename({'key_0' : '일자'},axis='columns')

In [26]:
data4.index = data4['일자']

In [30]:
data4 = data4.drop('일자', axis = 1)

In [31]:
data4.to_csv('20112020_data.csv')